export const chatTypes = {
	LOAD_USERS: "LOAD_USERS",
	GET_CHAT_USER: "GET_CHAT_USER",
	GET_MESSAGE: "GET_MESSAGE",
	GET_MESSAGES: "GET_MESSAGES",
	RESET_CHAT: "RESET_CHAT",
	SHOW_LIST_USER: "SHOW_LIST_USER",
	SHOW_TUTORIAL: "SHOW_TUTORIAL",
};
